sudo: required

language: c

services:
        - docker

git:
        submodules: false

before_install:
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init --recursive

install:
        - docker pull onkwon/yaos

script:
        - docker run -v $(pwd):/work onkwon/yaos make stm32f1-min
        - docker run -v $(pwd):/work onkwon/yaos make
        - docker run -v $(pwd):/work onkwon/yaos make test
        - docker run -v $(pwd):/work onkwon/yaos make coverage

after_success:
        - bash <(curl -s https://codecov.io/bash) -f tests/build/artifacts/gcov/report.xml
