ifeq ($(USE_CMSIS),y)
	CMSIS_INCS = \
		     -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include \
		     -I../Drivers/CMSIS/Include

	THIRD_PARTY_INCS += $(CMSIS_INCS)
endif

ifeq ($(USE_HAL),y)
	HAL_CFLAGS = -DUSE_HAL_DRIVER -DSTM32F429xx
	HAL_SRCS   = \
		     $(BASEDIR)/../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c \
		     $(BASEDIR)/../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c \
		     $(BASEDIR)/../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c \
		     $(BASEDIR)/../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
		     $(BASEDIR)/../Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
	HAL_INCS = \
		   -I$(BASEDIR)/../Drivers/STM32F4xx_HAL_Driver/Inc \
		   -I$(BASEDIR)/../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
		   -I$(BASEDIR)/../Drivers/Inc

	THIRD_PARTY_SRCS += $(HAL_SRCS:.c=.o)
	THIRD_PARTY_INCS += $(HAL_INCS)
	THIRD_PARTY_CFLAGS ?= $(CFLAGS)
	THIRD_PARTY_CFLAGS += $(HAL_CFLAGS)
endif

ifeq ($(USE_EMWIN),y)
	EMWIN_CFLAGS = $(CFLAGS) #-DOS_SUPPORT
	EMWIN_INCS = \
		     -I$(BASEDIR)/.. \
		     -I$(BASEDIR)/../emWin/inc

	LIBS += $(BASEDIR)/../emWin/Lib/STemWin540_CM4_GCC.a
	INCS += $(EMWIN_INCS)
endif
