SRCS_ASM = $(wildcard *.S)
SRCS     = $(wildcard *.c)
OBJS     = $(SRCS:%.c=%.o) $(SRCS_ASM:%.S=%.o)

INC      = -I$(BASEDIR)/include -I./include
LIBS    +=
CFLAGS  += $(INC) $(LIBS)

.SUFFIXES: .c.o
.SUFFIXES: .s.o
.SUFFIXES: .S.o

all: board $(OBJS)
ifdef BOARD
	$(LD) -o $(BOARD).o -r boards/$(BOARD)/*.o
endif

board:
ifdef BOARD
	@$(MAKE) --print-directory -C boards/$(BOARD)
endif

depend dep:
	echo $(CC)
	$(CC) $(CFLAGS) -MM $(SRCS) $(TARGET_SRCS) > .depend

clean:
	@rm -f $(OBJS) .depend
ifdef BOARD
	@rm -f $(BOARD).o
	@$(MAKE) clean -C boards/$(BOARD)
endif

ifneq ($(MAKECMDGOALS), clean)
ifneq ($(MAKECMDGOALS), depend)
ifneq ($(MAKECMDGOALS), dep)
ifneq ($(SRCS),)
-include .depend
endif
endif
endif
endif
